[package]
name = "mkpass"
version = "0.3.0"
authors = ["Thomas Hurst <tom@hur.st>"]
edition = "2018"

[dependencies]
rand = "0.8"
lazy_static = "1.4"
clap = { version = "4.1.6", features = ["derive"] }
